services:
  - type: web
    name: irambot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: LOG_LEVEL
        value: info
      - key: ENVIRONMENT
        value: production
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        sync: false # Usa el puerto proporcionado por Render
    plan: free
    autoDeploy: true
