"""create_initial_tables_and_add_user_state_fields

Revision ID: 6431794d6158
Revises: 
Create Date: 2025-05-15 00:27:03.977219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6431794d6158'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_wa_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_phone', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_company_id'), 'interactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_user_wa_id'), 'interactions', ['user_wa_id'], unique=False)
    op.create_table('user_states',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('current_brand_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('collected_name', sa.String(length=255), nullable=True),
    sa.Column('collected_phone', sa.String(length=50), nullable=True),
    sa.Column('collected_email', sa.String(length=255), nullable=True),
    sa.Column('purpose_of_inquiry', sa.Text(), nullable=True),
    sa.Column('location_info', sa.String(length=512), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_brand_id'], ['companies.id'], name='fk_user_states_company_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', 'platform')
    )
    op.create_index(op.f('ix_user_states_current_brand_id'), 'user_states', ['current_brand_id'], unique=False)
    op.create_index(op.f('ix_user_states_platform'), 'user_states', ['platform'], unique=False)
    op.create_index(op.f('ix_user_states_stage'), 'user_states', ['stage'], unique=False)
    op.create_index(op.f('ix_user_states_user_id'), 'user_states', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('calendly_event_uri', sa.Text(), nullable=False),
    sa.Column('calendly_invitee_uri', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_calendly_invitee_uri'), 'appointments', ['calendly_invitee_uri'], unique=True)
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_interaction_id'), 'appointments', ['interaction_id'], unique=True)
    op.create_index(op.f('ix_appointments_reminder_sent'), 'appointments', ['reminder_sent'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_constraint('companies_name_key', 'companies', type_='unique')
    op.drop_index('idx_companies_name', table_name='companies')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_table_comment(
        'companies',
        existing_comment='Almacena las diferentes empresas/marcas gestionadas por el bot',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'companies',
        'Almacena las diferentes empresas/marcas gestionadas por el bot',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False)
    op.create_unique_constraint('companies_name_key', 'companies', ['name'])
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_reminder_sent'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_interaction_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_calendly_invitee_uri'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_user_states_user_id'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_stage'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_platform'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_current_brand_id'), table_name='user_states')
    op.drop_table('user_states')
    op.drop_index(op.f('ix_interactions_user_wa_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_company_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
