"""add_is_subscribed_to_user_states

Revision ID: 8d1ff6b0205d
Revises: 6431794d6158
Create Date: 2025-05-15 22:42:33.558065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1ff6b0205d'
down_revision: Union[str, None] = '6431794d6158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_states', 
        sa.Column(
            'is_subscribed', 
            sa.Boolean(), 
            nullable=False,
            server_default=sa.text('true')  # <--- ESTA ES LA LÍNEA IMPORTANTE AÑADIDA/MODIFICADA
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_states', 'is_subscribed')
    # ### end Alembic commands ###